format = """
$schema\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_metrics\
$fill\
$cmd_duration $jobs $time\
$linebreak
$os\
$character
"""
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[os]
#format = '[$symbol](bold white) '
style = "bg:#1d2230"
format = '[$symbol](bg:#1C3A5E fg:#8DFBD2)($style) '
disabled = false

[os.symbols]
Windows = ' '
Arch = '󰣇 '
Ubuntu = ' '
Macos = ' 󰀵 '

[username]
format = '[$user]($style) '
disabled = false
show_always = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
#success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
success_symbol = '[➜](bold green) '
error_symbol = '[✗](#E84D44) '

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

[fill]
symbol = ' '
style = 'bold green'

[git_branch]
#symbol = ' '
symbol = " "
#format = 'via [$symbol$branch]($style)'
format = '[ $symbol$branch(:$remote_branch) ]($style)'
# truncation_length = 4
truncation_symbol = '…/'
#style = 'bold green'
style = "fg:#1C3A5E bg:#FCF392"

# Shows current directory
[directory]
truncation_length = 8
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '


[git_status]
format = '[$all_status]($style)'
style = "fg:#1C3A5E bg:#FCF392"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#FCF392"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
min_time = 500
format = 'underwent [$duration](bold yellow)'
style = "fg:bright-white bg:18"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
